## NumPy 

NumPy (https://numpy.org/doc/stable) is a library that extends the base capabilities of Python to add a richer data set including more numeric types, vectors, matrices and matrix functions. NumPy and Python work together fairly seamlessly - Python arithmetic operators work on NumPy data types and many NumPy functions will accept Python data types.

* NumPy basic datatype is an indexable, n-dimensional array, containing elements of the same type (check the type of data present with $dtype$)
* Vector in this context represents ordered array of numbers (with # of elements reffered to as 'dimension' or 'rank').
* Some NumPy routines for creating vectors take # of elements as arguments, others take a 'shape' tuple. 
* NumPy provides very complete set of indexing and slicing capabilities for accessing vector elements.

In [150]:
import numpy as np

# NumPy routines, which allocate memory and fill arrays with values.
# All examples have shape (4,) i.e. 1-D array with 4 elements for comparison purposes.

v = np.zeros(0)
print("np.zeros(0) =", v, v.shape, v.dtype, "\n")
v = np.zeros((4,))
print("np.zeros((4,)) =", v, v.shape, v.dtype, "\n")
v = np.random.random_sample((4,))  # uniform distribution over [0, 1)
print("np.random.random_sample((4,)) =", v, v.shape, v.dtype, "\n")    
v = np.random.rand(4)  # uniform distribution over [0, 1)
print("np.random.rand(4) =", v, v.shape, v.dtype, "\n")       
v = np.arange(4.)  # evenly spaced values.
print("np.arange(4.) =", v, v.shape, v.dtype, "\n")    
v = np.arange(0., 4, 1)  # start [optional, default = 0], stop, step [optional, default = 1]  
print("np.arange(0., 4, 1) =", v, v.shape, v.dtype, "\n")      
v = np.array([1, 2, 3, 4])
print("np.array([1, 2, 3, 4]) =", v, v.shape, v.dtype, "\n")     
v = np.array([1., 2., 3, 4])  # start [optional, default = 0], stop, step [optional, default = 1],
print("np.array([1., 2., 3, 4]) =", v, v.shape, v.dtype, "\n")     

# numpy.reshape gives a new shape to an array without changing its data. Returns the original array (it's a view, not a copy).
# The new shape as param should be compatible with the original shape.

arr = np.arange(24)
print(arr.shape)
# One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.
arr = arr.reshape(2,3,-1)
print(arr.shape)
# Turn back to original 1-D shape
arr = arr.reshape(-1)
print(arr.shape, "\n")
 
# Axis specifies which direction to perform the operation along; Example: np.sum(a, axis=0) calculates the sum of each column.
# The default, axis=None, will operate on all of the elements of the input array. 
# If axis is negative it counts from the last to the first axis. 
# If axis is a tuple of ints, a operation is performed on all of the axes specified in the tuple.

c = np.arange(0,16,1).reshape(2,2,4)
print("c =", c, "\n\n",
      "np.sum(c) =", np.sum(c), "\n", # sum all elements 
      "np.sum(c, axis=0) =", np.sum(c, axis=0), "\n",   
      "np.sum(c, axis=1) =", np.sum(c, axis=1), "\n",   
      "np.sum(c, axis=2) =", np.sum(c, axis=2), "\n",         
      "np.mean(c) =", np.mean(c), "\n", 
      "np.mean(c, axis=0) =", np.mean(c, axis=0), "\n"
     )


np.zeros(0) = [] (0,) float64 

np.zeros((4,)) = [0. 0. 0. 0.] (4,) float64 

np.random.random_sample((4,)) = [0.76850178 0.90838834 0.54804153 0.89855918] (4,) float64 

np.random.rand(4) = [0.03513744 0.09212483 0.86121123 0.50516394] (4,) float64 

np.arange(4.) = [0. 1. 2. 3.] (4,) float64 

np.arange(0., 4, 1) = [0. 1. 2. 3.] (4,) float64 

np.array([1, 2, 3, 4]) = [1 2 3 4] (4,) int32 

np.array([1., 2., 3, 4]) = [1. 2. 3. 4.] (4,) float64 

(24,)
(2, 3, 4)
(24,) 

c = [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 

 np.sum(c) = 120 
 np.sum(c, axis=0) = [[ 8 10 12 14]
 [16 18 20 22]] 
 np.sum(c, axis=1) = [[ 4  6  8 10]
 [20 22 24 26]] 
 np.sum(c, axis=2) = [[ 6 22]
 [38 54]] 
 np.mean(c) = 7.5 
 np.mean(c, axis=0) = [[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 



## Slicing

Slicing creates an array of indices  using a set of three values (start:stop:step). A subset of values is also valid.

In [160]:
# Indexing (refers 1 element by position) and slicing (refurs a subset based on indices) examples.
# Index must be withing vector range.

a = np.arange(10)
print("a =", a, "\n\n",
      "a[2] =", a[2], "\n", 
      "a[-1] =", a[-1], "\n", # laste element
      "a[2:7:2] =", a[2:7:2], "\n", # stat:stop:step
      "a[2:] =", a[2:], "\n", # all elements index 2 and above
      "a[:2] =", a[:2], "\n", # all elements below index 2
      "a[:] =", a[:], "\n", # all elements 
     )

# Create a shallow copy of an array (does not copy inner arrays)
b = a[:]

c = np.arange(20).reshape(-1,10)
print("c =", c, "\n\n",
      "c[0, 2:7:1] =", c[0, 2:7:1], "\n", # access 5 consecutive elements in row 0
      "c[:, 2:7:1] =", c[:, 2:7:1], "\n", # access 5 consecutive elements in two rows
      "c[:,:] =", c[:,:], "\n", # access all elements
      "c[1,:] =", c[1,:], "\n", # access all elements in row 1
      "c[1] =", c[1], "\n", # same as the above row
      "c[:,1] =", c[:,1], "\n", # access all elements in column 1
     )


a = [0 1 2 3 4 5 6 7 8 9] 

 a[2] = 2 
 a[-1] = 9 
 a[2:7:2] = [2 4 6] 
 a[2:] = [2 3 4 5 6 7 8 9] 
 a[:2] = [0 1] 
 a[:] = [0 1 2 3 4 5 6 7 8 9] 

c = [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] 

 c[0, 2:7:1] = [2 3 4 5 6] 
 c[:, 2:7:1] = [[ 2  3  4  5  6]
 [12 13 14 15 16]] 
 c[:,:] = [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] 
 c[1,:] = [10 11 12 13 14 15 16 17 18 19] 
 c[1] = [10 11 12 13 14 15 16 17 18 19] 
 c[:,1] = [ 1 11] 



## Vector operations

* Vectorization is a technique used to improve the performance of Python code by eliminating the use of loops. This feature provides a large speed up as NumPy makes a better use of the available parallelism in the underlying hardware. GPU and moden CPU's implement Single Instruction, Multiple Data (SIMD) piplines, allowing multiple operation to be issued in parallel. This has proven to be critical in ML, where the datasets are often very large.
* Most of NumPy arithmetic, logical and comparison operations apply to vectors as well and work emelement-wise (on an element-by-element basis). The requirement  for the vectors is to have the same shapes.
* The dot product of two vectors returns a scalar value and is calculated as:  $x = \sum_{i=0}^{n-1} a^{(i)}.b^{(i)}$

In [125]:
a = np.arange(10)
print("a =", a, "\n\n",
      "-a =", -a, "\n", 
      "a**2", a**2, "\n",  
      "a*2 =", a*2, "\n",  
      "a-2 =", a-2, "\n", 
     )

b = np.arange(10,20,1)
print("b =", b, "\n\n",
      "a + b =", a + b, "\n", 
      "a.dot(b) =", a.dot(b), "\n",  # dot product of two vectors  
      "np.dot(a, b) =", np.dot(a, b), "\n",
      "np.outer(a, b) =", np.outer(a, b), "\n", # outer (tensor) product (all possible distinct pairs of elements from a and b)
      "np.multiply(a, b) =", np.multiply(a, b)  # calculates the matrix product of two arrays: multiplication of "row by column"
     )


a = [0 1 2 3 4 5 6 7 8 9] 

 -a = [ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9] 
 a**2 [ 0  1  4  9 16 25 36 49 64 81] 
 a*2 = [ 0  2  4  6  8 10 12 14 16 18] 
 a-2 = [-2 -1  0  1  2  3  4  5  6  7] 

b = [10 11 12 13 14 15 16 17 18 19] 

 a + b = [10 12 14 16 18 20 22 24 26 28] 
 a.dot(b) = 735 
 np.dot(a, b) = 735 
 np.outer(a, b) = [[  0   0   0   0   0   0   0   0   0   0]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  22  24  26  28  30  32  34  36  38]
 [ 30  33  36  39  42  45  48  51  54  57]
 [ 40  44  48  52  56  60  64  68  72  76]
 [ 50  55  60  65  70  75  80  85  90  95]
 [ 60  66  72  78  84  90  96 102 108 114]
 [ 70  77  84  91  98 105 112 119 126 133]
 [ 80  88  96 104 112 120 128 136 144 152]
 [ 90  99 108 117 126 135 144 153 162 171]] 
 np.multiply(a, b) = [  0  11  24  39  56  75  96 119 144 171]


## Example: vectorization vs for-loop

In [148]:
import time

np.random.seed(1)  # Reseed the singleton RandomState instance.
size = 10**6  
a = np.random.rand(size) # very large array
b = np.random.rand(size)  

start = time.time()
result = np.dot(a,b)
stop = time.time()
print(f"Vectorized version duration for dot(a,b) = {result} : {1000*(stop-start):.4f} ms")

start = time.time() 
result = np.sum( [a[i] * b[i] for i in range(a.shape[0])] )
stop = time.time()
print(f"For-loop version duration for dot(a,b) = {result} : {1000*(stop-start):.4f} ms")

Vectorized version duration for dot(a,b) = 249825.02337924892 : 1.0281 ms
For-loop version duration for dot(a,b) = 249825.0233792488 : 211.9670 ms


## Broadcasting

> The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array (or scalar) is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation. 

> If an array and a scalar are combined in an opration - the scalar is virtually "stretched" to match the shape of the array. 

> When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing i.e. the rightmost dimension and works its way left. Two dimensions are compatible when: A) they are equal, or B) one of them is 1. When the trailing dimensions of the arrays are unequal, broadcasting fails because it is impossible to align the values in the rows of the 1st array with the elements of the 2nd arrays for element-by-element addition.

> Input arrays do not need to have the same number of dimensions. The resulting array will have the same number of dimensions as the input array with the greatest number of dimensions, where the size of each dimension is the largest size of the corresponding dimension among the input arrays. Dimensions with size 1 are stretched or “copied” to match the other. Missing dimensions are also assumed to have size on1. 

> For example, if a.shape is (5,1), b.shape is (1,6), c.shape is (6,) and d.shape is () so that d is a scalar, then a, b, c, and d are all broadcastable to dimension (5,6); and


In [78]:
a = np.array([1, 2, 3])
b = np.int_(4)
print(a.shape, "*", b.shape, " = ", (a*b).shape)

a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3])
#  operands could not be broadcast together with shapes (4,) (3,) 
#  print(a.shape, "*", b.shape, " = ", (a*b).shape)
anew = a[:, np.newaxis]
print(anew.shape, "*", b.shape, " = ", (anew*b).shape) 

a = np.array([[1], [1]])
b = np.array([[7, 1, 5], [7, 1, 5]]) 
print(a.shape, "*", b.shape, " = ", (a*b).shape)

a = np.array([
    [ [ [1],[2],[3],[4],[5],[6] ] ],
    [ [ [1],[2],[3],[4],[5],[6] ] ], 
    [ [ [1],[2],[3],[4],[5],[6] ] ],
    [ [ [1],[2],[3],[4],[5],[6] ] ], 
    [ [ [1],[2],[3],[4],[5],[6] ] ], 
    [ [ [1],[2],[3],[4],[5],[6] ] ], 
    [ [ [1],[2],[3],[4],[5],[6] ] ], 
    [ [ [1],[2],[3],[4],[5],[6] ] ]
      ])
b = np.array([
    [ [1,2,3,4,5] ],
    [ [1,2,3,4,5] ],
    [ [1,2,3,4,5] ],
    [ [1,2,3,4,5] ],
    [ [1,2,3,4,5] ],
    [ [1,2,3,4,5] ],
    [ [1,2,3,4,5] ]
      ])
print(a.shape, "*", b.shape, " = ", (a*b).shape)


(3,) * ()  =  (3,)
(4, 1) * (3,)  =  (4, 3)
(2, 1) * (2, 3)  =  (2, 3)
(8, 1, 6, 1) * (7, 1, 5)  =  (8, 7, 6, 5)
